inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "**/Gemfile"
    - "vendor/**/*"
    - ".git/**/*"
    - "spec/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 120
