version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      SELENIUM_DRIVER_URL: "http://selenium_chrome:4444/wd/hub"
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/renraku_app
    depends_on:
      - db
      - chrome
      - redis
    networks:
      - default
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/renraku_app
      - ./data/redis:/data
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  mysql_data:
